name: Continuous Deployment Test

on:
  push:
    branches: ["main", "main-workflow-test"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read # Allow reading repository contents
  pages: write   # Allow writing to the GitHub Pages deployment
  id-token: write # Allow authentication for OIDC (needed by deploy-pages)

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    # No 'environment' block here. The build job doesn't deploy directly.
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0" # Sticking to your requested specific version

      - name: Install dependencies
        run: npm ci
        
      - name: Build Static Files
        run: npm run build

      # The configure-pages action is generally more useful when you want to
      # explicitly configure the build source for Pages *before* deploying,
      # or if you are doing a single-job deployment. In this two-job
      # setup, deploy-pages handles the final configuration.
      # You can keep it, but it's not strictly essential for this flow.
      - name: Setup Pages # This step might be redundant if deploy-pages handles everything.
        uses: actions/configure-pages@v5

      - name: Upload GitHub Pages artifact # This is correct for the build job
        uses: actions/upload-pages-artifact@v3 # Use v4 if available
        with:
          path: ./dist/portifolio/browser # Ensure this matches your build output directory

  deploy:
    environment: # <-- This environment block belongs here, in the deploy job
      name: github-pages # Name of the deployment environment (must be 'github-pages')
      url: ${{ steps.deployment.outputs.page_url }} # URL will be populated by the deploy-pages action
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job completing successfully

    steps:
      - name: Deploy to GitHub Pages # Step 6: Deploy the uploaded artifact to GitHub Pages
        id: deployment # Assign an ID to this step to access its outputs
        uses: actions/deploy-pages@v4 # Use v5 if available